### ISSUE TITLE
other equipment unplugging

### ISSUE THREAD

**Issue by lisicn** [justengel/pyjoystick#2]
When I was executing a simple get script, I tried to unplug it, then unplug the wired keyboard, and then plug them in again. The result was that the keyboard did not respond, and the joystick did not respond; when I switched the keyboard to a wireless keyboard, The switch on the keyboard does not affect it, and there will be no response once the keyboard receiver is pulled out. They will work normally only after stopping main.py for a while. Sir, do you know why this is?

on windows system
```code
from pyjoystick.sdl2 import Key, Joystick, run_event_loop, get_mapping, set_mapping, get_mapping_name

devices = Joystick.get_joysticks()
print("Devices:", devices)

check_device = True

monitor = devices[0]
monitor_keytypes = [Key.AXIS]


def print_add(joy):
    print('Added', joy)

def print_remove(joy):
    print('Removed', joy)

def key_received(key):

    print('Key:', key, 'value:', key.value)

run_event_loop(print_add, print_remove, key_received)
```

**Comment by justengel** [comment]
When you unplug the controller you should see that the joystick was removed. When the joystick is plugged in you should see that the joystick was added. This library does not use keyboard events.

I was able to run the code you gave without a problem. When I unplugged the joystick `Removed Xbox 360 Controller` was printed. When I plugged the joystick in `Added Xbox 360 Controller` was printed and the joystick keys printed as I pressed buttons. You might want to look at the SDL2 library and write your own event loop if you need keyboard events.  This library is just a wrapper around sdl2  https://wiki.libsdl.org/APIByCategory.

**Comment by lisicn** [comment]
thanks for your answer
