### ISSUE TITLE
Doesnt work on Raspberry Pi 4

### ISSUE THREAD

**Issue by pavlosharhan2** [justengel/pyjoystick#4]
Any ideas why?
I tried It on Ubuntu and works like a charm. Want to make it work On RPi as well

**Comment by justengel** [comment]
Depends on what backend you are using. I primarily use sdl2, but I have some support for pygame. With either backend you have to figure out how to install it on your raspberry pi. This is just a python wrapper around the python sdl2 wrapper and pygame backends.

Once you confirm pygame or sdl2 runs then this library should work. The only thing this library might need for sdl2 support is pointing to the correctly compiled sdl2 files. I created a resource_man library to handle packaging and access the binary files.


```
# my_package/sdl2/__init__.py
# Have your compiled SDL2 files in this directory
import resource_man

SDL2_RASPI = resource_man.register('my_package.sdl2', 'SDL2.o')
```

```
# File that runs the code
from my_package.sdl2 import SDL2_RASPI

with SDL2_RASPI.as_file() as sdl_dll:
        os.environ.setdefault('PYSDL2_DLL_PATH', os.path.dirname(str(sdl_dll)))
        import sdl2
        
import pyjoystick
```

See Also [SDL2 Pathing](https://github.com/justengel/pyjoystick/blob/master/pyjoystick/sdl2.py#:~:text=%23%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%20SDL2%20Pathing%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D,END%20SDL2%20Pathing%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D)
