### ISSUE TITLE
doesnot work with exe files compiled with pyinstaller

### ISSUE THREAD

**Issue by llllllIIIII111lllIIllIIlIIIl** [justengel/pyjoystick#6]
It works before compilation, but after compilation the key_received function is not executed
Any ideas?
I tried with python 3.11.5 and 3.12.0 and both did not work.

**Comment by Chechere** [comment]
> It works before compilation, but after compilation the key_received function is not executed Any ideas? I tried with python 3.11.5 and 3.12.0 and both did not work.

I managed to make it work by changing this piece of code on sdl2.py:
```python
if check_os('win') and is_64_bit():
    with SDL2_WIN64.as_file() as sdl_dll:
        os.environ.setdefault('PYSDL2_DLL_PATH', os.path.dirname(str(sdl_dll)))
        import sdl2
elif check_os('win'):
    with SDL2_WIN32.as_file() as sdl_dll:
        os.environ.setdefault('PYSDL2_DLL_PATH', os.path.dirname(str(sdl_dll)))
        import sdl2
else:
    import sdl2
```

with:
```python
def sdl_dll_path(dll):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
        return os.path.join(base_path, dll)
    except Exception:
        return os.path.dirname(dll)    


if check_os('win') and is_64_bit():
    with SDL2_WIN64.as_file() as sdl_dll:
        # os.environ.setdefault('PYSDL2_DLL_PATH', os.path.dirname(str(sdl_dll)))
        os.environ.setdefault('PYSDL2_DLL_PATH', sdl_dll_path(str(sdl_dll)))
        import sdl2
elif check_os('win'):
    with SDL2_WIN32.as_file() as sdl_dll:
        os.environ.setdefault('PYSDL2_DLL_PATH', os.path.dirname(str(sdl_dll)))
        import sdl2
else:
    import sdl2
```

Then, in the pyinstaller command I added this: 
`--add-binary "<venv folder>\Lib\site-packages\pyjoystick\sdl2_win64\SDL2.dll:."`

It only works for 64bits. If you need for 32bit change the pyinstaller command with:
`--add-binary "<venv folder>\Lib\site-packages\pyjoystick\sdl2_win32\SDL2.dll:."`

It's a dirty solution, but I hope it works for you too.
Greetings

**UPDATE:**
I made it work only adding this to the pyinstaller command:
`--add-binary "<venv_folder>\Lib\site-packages\pyjoystick\sdl2_win32\SDL2.dll:pyjoystick\sdl2_win32"`
`--add-binary "<venv_folder>\Lib\site-packages\pyjoystick\sdl2_win64\SDL2.dll:pyjoystick\sdl2_win64"`

**Comment by llllllIIIII111lllIIllIIlIIIl** [comment]
It worked!!!
Thanks for the reply.
I respect you!!!
